name: SPHINCS+-shake-256f-simple
type: signature
claimed-nist-level: 5
length-public-key: 64
length-secret-key: 128
length-signature: 49856
testvectors-sha256: 770d6804113bb617b484bdc86c75b7aef08ea04d522d0f9ec645e121368cdc4e
nistkat-sha256: f6d0825afeb4ce25943c974a0efde5659ceea927d2507b0ea1a92e092f536acd
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
  - name: avx2
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
    supported_platforms:
      - architecture: x86_64
        required_flags: ['avx2']
  - name: aarch64
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
    supported_platforms:
      - architecture: arm_8
        required_flags: ['sha3']
        operating_systems:
          - Linux
          - Darwin
