name: SPHINCS+-sha2-256s-simple
type: signature
claimed-nist-level: 5
length-public-key: 64
length-secret-key: 128
length-signature: 29792
testvectors-sha256: 945a6d782c97e61d74552694a0f9e3bfc8ae0b7c03b86293da21a384acdbbd46
nistkat-sha256: 05d15a74253962d35912bab3a9ee3230c2e721c798f4e757ecffa529071b0748
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
  - name: avx2
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
    supported_platforms:
      - architecture: x86_64
        required_flags: ['avx2']
