name: ntruhrss701
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 1138
length-secret-key: 1450
length-ciphertext: 1138
length-shared-secret: 32
nistkat-sha256: 501e000c3eb374ffbfb81b0f16673a6282116465936608d7d164b05635e769e8
principal-submitters:
  - John M. Schanck
auxiliary-submitters:
  - Cong Chen
  - Oussama Danba
  - Jeffrey Hoffstein
  - Andreas Hülsing
  - Joost Rijneveld
  - Tsunekazu Saito
  - Peter Schwabe
  - William Whyte
  - Keita Xagawa
  - Takashi Yamakawa
  - Zhenfei Zhang
implementations:
    - name: clean
      version: https://github.com/jschanck/ntru/tree/3227cd42 reference implementation
    - name: avx2
      version: https://github.com/jschanck/ntru/tree/3227cd42 avx2 implementation
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
                - bmi2
