name: ntru-hrss701
type: kem
claimed-nist-level: 3
length-public-key: 1138
length-secret-key: 1450
length-ciphertext: 1138
length-shared-secret: 32
testvectors-sha256: a0082a6607ab054c296a02e1bea1b5d7ee8465077ee7989ab4295f9e464d0558
nistkat-sha256: 501e000c3eb374ffbfb81b0f16673a6282116465936608d7d164b05635e769e8
principal-submitter: John M. Schanck
auxiliary-submitters:
  - Cong Chen
  - Oussama Danba
  - Jeffrey Hoffstein
  - Andreas Hülsing
  - Joost Rijneveld
  - Peter Schwabe
  - William Whyte
  - Zhenfei Zhang
implementations:
    - name: clean
      version: https://csrc.nist.gov/CSRC/media/Projects/Post-Quantum-Cryptography/documents/round-2/submissions/NTRU-Round2.zip reference implemntation
