name: HQC-256
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-ciphertext: 17379
length-public-key: 8698
length-secret-key: 8738
length-shared-secret: 64
nistkat-sha256: c940cddc7be19d005a23e7a0b3b4079250fec682d09d093dbcff0bc23a3b9dc4
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Olivier Blazy
  - Jurjen Bos
  - Jean-Christophe Deneuville
  - Philippe Gaborit
  - Edoardo Persichetti
  - Jean-Marc Robert
  - Pascal Véron
  - Gilles Zémor
  - Loïc Bidoux
implementations:
    - name: clean
      version: hqc-submission_2020-05-29 via https://github.com/jschanck/package-pqclean/tree/09ab89ed/hqc
    - name: avx2
      version: hqc-submission_2020-05-29 via https://github.com/jschanck/package-pqclean/tree/09ab89ed/hqc
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
                - bmi1
                - pclmul
