name: HQC-256
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-ciphertext: 14421
length-public-key: 7245
length-secret-key: 7317
length-shared-secret: 64
nistkat-sha256: e89c520e1ac615ecf6923f211569177c536a89bf94bebf85bb263528282092c4
nistkat-rng: hqc
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jurjen Bos
  - Jean-Christophe Deneuville
  - Arnaud Dion
  - Philippe Gaborit
  - Jérôme Lacan
  - Edoardo Persichetti
  - Jean-Marc Robert
  - Pascal Véron
  - Gilles Zémor
implementations:
    - name: clean
      version: hqc-submission_2023-04-30 via https://github.com/SWilson4/package-pqclean/tree/9b509aa7/hqc
