name: Dilithium5-R
type: signature
claimed-nist-level: 5
length-public-key: 2592
length-secret-key: 4880
length-signature: 4595
nistkat-sha256: fcf4549d83865c839b2afca72d600836ec7a20f8a4aa27c5d57c863b41970f9c
testvectors-sha256: 76b2db0ded18c05988748b42d32d43975050fc3a644073278b169dde1d068772
principal-submitters:
  - Vadim Lyubashevsky
auxiliary-submitters:
  - Shi Bai
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Peter Schwabe
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://csrc.nist.gov/CSRC/media/Projects/post-quantum-cryptography/documents/round-3/submissions/Dilithium-Round3.zip
    - name: avx2
      version: https://csrc.nist.gov/CSRC/media/Projects/post-quantum-cryptography/documents/round-3/submissions/Dilithium-Round3.zip
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Darwin
                - Linux
            required_flags:
                - avx2
                - bmi1
                - popcnt