name: MamaBearEphem
type: kem
claimed-nist-level: 3
claimed-security: IND-CPA
length-public-key: 1194 
length-ciphertext: 1307
length-secret-key: 40
length-shared-secret: 32
nistkat-sha256: ef94f0f6471a1276efd9e019195489661c2356027fc2e8163e3718a1df027123 
principal-submitters:
  - Mike Hamburg
implementations:
    - name: clean
      version: https://sourceforge.net/p/threebears/code/ci/f4ce0ebfc84a5e01a75bfc8297b6d175e993cfa4/
