# This Makefile can be used with Microsoft Visual Studio's nmake using the command:
#    nmake /f Makefile.Microsoft_nmake

LIBRARY=libqtesla-p-I_clean.lib
OBJECTS=consts.obj gauss.obj pack.obj poly.obj sample.obj sign.obj

CFLAGS=/nologo /I ..\..\..\common /W4 /WX

all: $(LIBRARY)

# Make sure objects are recompiled if headers change.
$(OBJECTS): *.h

$(LIBRARY): $(OBJECTS)
	LIB.EXE /NOLOGO /WX /OUT:$@ $**

clean:
    -DEL $(OBJECTS)
    -DEL $(LIBRARY)
