KeccakP-1600-times4-SIMD256.obj: KeccakP-1600-times4-SIMD256.c \
  align.h brg_endian.h KeccakP-1600-times4-SnP.h \
  KeccakP-1600-unrolling.macros SIMD256-config.h
	$(CC) /nologo /c /O2 /W4 /WX /arch:AVX2 KeccakP-1600-times4-SIMD256.c

.PHONY: clean
clean:
	$(RM) KeccakP-1600-times4-SIMD256.obj
