name: HQC_192_1_CCA2
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 5499
length-ciphertext: 10981
length-secret-key: 5539
length-shared-secret: 64
nistkat-sha256: ddff72bfd7bf33a9fa1b3c70a05378b0544e57207b5bb9205cacd6d69002d597
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jean-Christophe Deneuville
  - Philippe Gaborit
  - Edoardo Persichetti
  - Gilles Zémor
auxiliary-submitters: []
implementations:
  - name: leaktime
    version: https://pqc-hqc.org/doc/hqc-reference-implementation_2019-08-24.zip
