name: PapaBearEphem
type: kem
claimed-nist-level: 5
claimed-security: IND-CPA
length-public-key: 1584 
length-ciphertext: 1697
length-secret-key: 40
length-shared-secret: 32
nistkat-sha256: afe40a1172ab5f4f87135297e0a7c67047d21c87f33ab518864c030820c3674d 
principal-submitters:
  - Mike Hamburg
implementations:
    - name: clean
      version: https://sourceforge.net/p/threebears/code/ci/f4ce0ebfc84a5e01a75bfc8297b6d175e993cfa4/
