name: Classic McEliece 8192128
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 1357824
length-secret-key: 14120
length-ciphertext: 208
length-shared-secret: 32
nistkat-sha256: cbe9b802465df7a7b3a59a08d3bd3ea603b6277532c15f89418b8d0d6508ee24
principal-submitters:
  - Daniel J. Bernstein
  - Tung Chou
  - Tanja Lange
  - Ingo von Maurich
  - Rafael Misoczki
  - Ruben Niederhagen
  - Edoardo Persichetti
  - Christiane Peters
  - Peter Schwabe
  - Nicolas Sendrier
  - Jakub Szefer
  - Wen Wang
auxiliary-submitters: []
implementations:
    - name: clean
      version: SUPERCOP-20221025
    - name: avx2
      version: SUPERCOP-20221025
      supported_platforms:
        - architecture: x86_64
          operating_systems:
            - Linux
            - Darwin
          required_flags:
            - avx2
            - popcnt