name: SPHINCS+-sha2-128s-simple
type: signature
claimed-nist-level: 1
length-public-key: 32
length-secret-key: 64
length-signature: 7856
testvectors-sha256: 8d6bb7a5a5c02a11b2be5feab0a837344241bf0b9222102b8d55d3e45bfdc3db
nistkat-sha256: 08c2e0f08bd96f50d065ca0ced04874c709d192864bfeaccb6daa4bfa9c58a28
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
  - name: avx2
    version: https://github.com/sphincs/sphincsplus/commit/ed15dd78658f63288c7492c00260d86154b84637
    supported_platforms:
      - architecture: x86_64
        required_flags: ['avx2']
