name: SPHINCS+
type: signature
claimed-nist-level: 1
length-public-key: 32
length-secret-key: 64
length-signature: 16976
testvectors-sha256: 3e7c782b25e405940160468c2d777a5ab6eb9b6cfe318efed257f3270cca8c72
nistkat-sha256: cf7935fc0277099a7453f6c5dc54e40d5cf34fbe989909940a77a3fbbab6c42e
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
implementations:
    - name: clean
      version: https://github.com/sphincs/sphincsplus/commit/77755c94d0bc744478044d6efbb888dc13156441
    - name: avx2
      version: https://github.com/sphincs/sphincsplus/commit/77755c94d0bc744478044d6efbb888dc13156441
      supported_platforms:
        - architecture: x86_64
          required_flags:
            - avx2
