name: Classic McEliece 6960119
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 1047319
length-secret-key: 13948
length-ciphertext: 194
length-shared-secret: 32
nistkat-sha256: 8feea532732502134b7965fd495e6618b09f0b4747c2d94b29a85a90a0b6cc8a
principal-submitters:
  - Daniel J. Bernstein
  - Tung Chou
  - Tanja Lange
  - Ingo von Maurich
  - Rafael Misoczki
  - Ruben Niederhagen
  - Edoardo Persichetti
  - Christiane Peters
  - Peter Schwabe
  - Nicolas Sendrier
  - Jakub Szefer
  - Wen Wang
auxiliary-submitters: []
implementations:
    - name: clean
      version: SUPERCOP-20221025
    - name: avx2
      version: SUPERCOP-20221025
      supported_platforms:
        - architecture: x86_64
          operating_systems:
            - Linux
            - Darwin
          required_flags:
            - avx2
            - popcnt