name: MQDSS-48
type: signature
claimed-nist-level: 1
length-public-key: 46
length-secret-key: 16
length-signature: 28400
nistkat-sha256: 9ca5c44144cfbf554748a1278f1abfdc97ae2ac4615561f2004c3f234c452d82
testvectors-sha256: 9a2413984acd79b59d7270d0c05fbd1396a933f334362638fc2a1e7271f733f2
principal-submitters:
  - Simona Samardjiska
auxiliary-submitters:
  - Ming-Shing Chen
  - Andreas Hülsing
  - Joost Rijneveld
  - Peter Schwabe
implementations:
    - name: clean
      version: https://github.com/joostrijneveld/MQDSS/commit/00608d7610262ff07b1834885d32bc3fd27ef5e1
    - name: avx2
      version: https://github.com/joostrijneveld/MQDSS/commit/00608d7610262ff07b1834885d32bc3fd27ef5e1
      supported_platforms:
          - architecture: x86_64
            required_flags:
                - avx2
          - architecture: x86
            required_flags:
                - avx2
