name: MQDSS-64
type: signature
claimed-nist-level: 3
length-public-key: 64
length-secret-key: 24
length-signature: 59928
nistkat-sha256: afdfc887ec7d0ee648ea3802310ccff92ce0ed1f9c96d9d47ae3d5cf602785fd
testvectors-sha256: ff8afac3a7d4bbb8c088c23d12fdc0e0c3bc8aace57386ac20ac0a65ae4f3e68
principal-submitters:
  - Simona Samardjiska
auxiliary-submitters:
  - Ming-Shing Chen
  - Andreas Hülsing
  - Joost Rijneveld
  - Peter Schwabe
implementations:
    - name: clean
      version: https://github.com/joostrijneveld/MQDSS/commit/00608d7610262ff07b1834885d32bc3fd27ef5e1
