name: gemss-blue-256
type: signature
claimed-nist-level: 5
length-public-key: 3087963
length-secret-key: 32
length-signature: 74
nistkat-sha256: ae7777b16435db97b3b7d8e5bf86e321ba2c44b8841a7042ea43ea77b5a6fc87
testvectors-sha256: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
principal-submitters:
  - A. Casanova
  - J.-C. Faugere
  - G. Macario-Rat
  - J. Patarin
  - L. Perret
  - J. Ryckeghem
implementations:
    - name: clean
      version: GeMSS-Round2_V2.a
    - name: avx2
      version: GeMSS-Round2_V2.a
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
