name: gemss-red-192
type: signature
claimed-nist-level: 3
length-public-key: 1290543
length-secret-key: 24
length-signature: 55
nistkat-sha256: a3edfab4e1387318d720589d7173a5df5221b611d4aac70ac1f9c41e31da2223
testvectors-sha256: b6b18406f3be5e845454ce73ab6d11221cf21b18ec098db16d6e227d3a7a6185
principal-submitters:
  - A. Casanova
  - J.-C. Faugere
  - G. Macario-Rat
  - J. Patarin
  - L. Perret
  - J. Ryckeghem
implementations:
    - name: clean
      version: GeMSS-Round2_V2.a
    - name: avx2
      version: GeMSS-Round2_V2.a
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
