name: HQC-192
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-ciphertext: 8978
length-public-key: 4522
length-secret-key: 4586
length-shared-secret: 64
nistkat-sha256: 771c5e421c4eea951850d5883e2329c40783a3c0f363d8dc8e1be7c4026d1ab7
nistkat-rng: hqc
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jurjen Bos
  - Jean-Christophe Deneuville
  - Arnaud Dion
  - Philippe Gaborit
  - Jérôme Lacan
  - Edoardo Persichetti
  - Jean-Marc Robert
  - Pascal Véron
  - Gilles Zémor
implementations:
    - name: clean
      version: hqc-submission_2023-04-30 via https://github.com/SWilson4/package-pqclean/tree/9b509aa7/hqc
