name: HQC_256_3_CCA2
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 8897
length-ciphertext: 17777
length-secret-key: 8937
length-shared-secret: 64
nistkat-sha256: e0bb4e73a1a27f05ddb1138685922bf4a40c2e535b5152b93135c06a73777770
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jean-Christophe Deneuville
  - Philippe Gaborit
  - Edoardo Persichetti
  - Gilles Zémor
auxiliary-submitters: []
implementations:
  - name: leaktime
    version: https://pqc-hqc.org/doc/hqc-reference-implementation_2019-08-24.zip
