name: ntru-hps2048509
type: kem
claimed-nist-level: 1
length-public-key: 699
length-ciphertext: 699
length-shared-secret: 32
testvectors-sha256: 2f5cf9937959eb4a3bc910f71e830e9e0de029b28093c6192d2c3e915913016f
principal-submitter: John M. Schanck
auxiliary-submitters:
  - Cong Chen
  - Oussama Danba
  - Jeffrey Hoffstein
  - Andreas Hülsing
  - Joost Rijneveld
  - Peter Schwabe
  - William Whyte
  - Zhenfei Zhang
implementations:
    - name: clean
      version: https://csrc.nist.gov/CSRC/media/Projects/Post-Quantum-Cryptography/documents/round-2/submissions/NTRU-Round2.zip reference implemntation
      length-secret-key: 935
