name: Dilithium5-AES
type: signature
claimed-nist-level: 5
length-public-key: 2592
length-secret-key: 4864
length-signature: 4595
nistkat-sha256: 5734f0f32acf7190130448bbc121994a29fa4355deeee167ef65dbed014f6ee0
nistkat-rng: nist
testvectors-sha256: e790f11f4951965d38283f9a4440837c3158bd60c89bbe43807bad41095f1c39
principal-submitters:
  - Vadim Lyubashevsky
auxiliary-submitters:
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Peter Schwabe
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://github.com/pq-crystals/dilithium/commit/61b51a71701b8ae9f546a1e5d220e1950ed20d06 via https://github.com/jschanck/package-pqclean/tree/98146649/dilithium
    - name: avx2
      version: https://github.com/pq-crystals/dilithium/commit/61b51a71701b8ae9f546a1e5d220e1950ed20d06 via https://github.com/jschanck/package-pqclean/tree/98146649/dilithium
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - aes
              - avx2
              - popcnt
