name: Dilithium3
type: signature
claimed-nist-level: 3
length-public-key: 1952
length-secret-key: 4032 
length-signature: 3309
nistkat-sha256: 4ae9921a12524a31599550f2b4e57b6db1b133987c348f07e12d20fc4aa426d5
testvectors-sha256: 4488a45fa13d1c286989739a014fecd615b0ec1f1c07ea1a0df876c7b5151116
principal-submitters:
  - Vadim Lyubashevsky
auxiliary-submitters:
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Peter Schwabe
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://github.com/pq-crystals/dilithium/commit/918af1a6eaedcedf9fdd8aaaca6c1fccd5a7a51f via https://github.com/mkannwischer/package-pqclean/tree/0e93c0323cf84af6b437496ddae73a4cb79a6bcd/dilithium
    - name: avx2
      version: https://github.com/pq-crystals/dilithium/commit/918af1a6eaedcedf9fdd8aaaca6c1fccd5a7a51f via https://github.com/mkannwischer/package-pqclean/tree/0e93c0323cf84af6b437496ddae73a4cb79a6bcd/dilithium
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - aes
              - avx2
              - popcnt

    - name: aarch64
      version: https://github.com/neon-ntt/neon-ntt/tree/f88c7dd2bf03fb0dbdcccbf2fe437f7bb0a77441
      supported_platforms:
        - architecture: arm_8
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - asimd