name: FireSaber
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 1312
length-ciphertext: 1472
length-secret-key: 3040
length-shared-secret: 32
nistkat-sha256: 937d9b2e139112e13d4093a6afe715deff476e4d578208b9e8e1809de43835cd
principal-submitters:
  - Jan-Pieter D'Anvers
  - Angshuman Karmakar
  - Sujoy Sinha Roy
  - Frederik Vercauteren
implementations:
    - name: clean
      version: https://github.com/KULeuven-COSIC/SABER/tree/509cc5ec3a7e12a751ccdd2ef5bd6e54e00bd350 via https://github.com/jschanck/package-pqclean/tree/1ae84c3c/saber
    - name: avx2
      version: https://github.com/KULeuven-COSIC/SABER/tree/509cc5ec3a7e12a751ccdd2ef5bd6e54e00bd350 via https://github.com/jschanck/package-pqclean/tree/1ae84c3c/saber
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
