name: SPHINCS+-shake-128s-simple
type: signature
claimed-nist-level: 1
length-public-key: 32
length-secret-key: 64
length-signature: 7856
testvectors-sha256: 196afac73e8f3d587567685611f85717c1595ab45e7d4b20c9f3d3495d631d20
nistkat-sha256: bae2979565dabad96d885a1e264bc213ab54aff3c3b4308880b788e87702af3b
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Ward Beullens
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
  - Bas Westerbaan
implementations:
  - name: clean
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
  - name: avx2
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
    supported_platforms:
      - architecture: x86_64
        required_flags: ['avx2']
  - name: aarch64
    version: https://github.com/mkannwischer/sphincsplus/tree/ae132f7bf9f90205834c1cbdf5cfb9187d51f48e
    supported_platforms:
      - architecture: arm_8
        required_flags: ['sha3']
        operating_systems:
          - Linux
          - Darwin
