name: Falcon-512
type: signature
claimed-nist-level: 1
length-public-key: 897
length-secret-key: 1281
length-signature: 690
nistkat-sha256: e9c3985f1ce732e29ca81aeca091f20d4dbb5beb456ee1a7ab41d04add4dab10
testvectors-sha256: 036b5e803ab825146502513b7460b24cc9493f8e366323cd5e30e2dc6d4ca6a7
principal-submitters:
  - Thomas Prest
auxiliary-submitters:
  - Pierre-Alain Fouque
  - Jeffrey Hoffstein
  - Paul Kirchner
  - Vadim Lyubashevsky
  - Thomas Pornin
  - Thomas Ricosset
  - Gregor Seiler
  - William Whyte
  - Zhenfei Zhang
implementations:
    - name: clean
      version: supercop-20201018 via https://github.com/jschanck/package-pqclean/tree/78831f03/falcon
    - name: avx2
      version: supercop-20201018 via https://github.com/jschanck/package-pqclean/tree/78831f03/falcon
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
