name: Saber
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 992
length-ciphertext: 1088
length-secret-key: 2304
length-shared-secret: 32
nistkat-sha256: c9e2c16f41f162c607a1d5704107159e5e12713b9bb8c356b1d68b216e79096e
principal-submitters:
  - Jan-Pieter D'Anvers
  - Angshuman Karmakar
  - Sujoy Sinha Roy
  - Frederik Vercauteren
implementations:
    - name: clean
      version: https://github.com/KULeuven-COSIC/SABER/tree/509cc5ec3a7e12a751ccdd2ef5bd6e54e00bd350 via https://github.com/jschanck/package-pqclean/tree/1ae84c3c/saber
    - name: avx2
      version: https://github.com/KULeuven-COSIC/SABER/tree/509cc5ec3a7e12a751ccdd2ef5bd6e54e00bd350 via https://github.com/jschanck/package-pqclean/tree/1ae84c3c/saber
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
