---
name: Falcon-512 (PADDED)
type: signature
claimed-nist-level: 1
length-public-key: 897
length-secret-key: 1281
length-signature: 666
nistkat-sha256: da27fe8a462de7307ddf1f9b00072a457d9c5b14e838c148fbe2662094b9a2ca
testvectors-sha256: a380380196d874a5ecd3616e17a807dd58674b7f5456e21140564d503a8610e1
principal-submitters:
  - Thomas Prest
auxiliary-submitters:
  - Pierre-Alain Fouque
  - Jeffrey Hoffstein
  - Paul Kirchner
  - Vadim Lyubashevsky
  - Thomas Pornin
  - Thomas Prest
  - Thomas Ricosset
  - Gregor Seiler
  - William Whyte
  - Zhenfei Zhang
implementations:
  - name: clean
    version: 20211101 with PQClean patches
  - name: avx2
    version: 20211101 with PQClean patches
    supported_platforms:
      - architecture: x86_64
        required_flags:
          - avx2
  - name: aarch64
    version: https://github.com/cothan/Falcon-Arm/commit/9aaea0318bb2aa409239246ff847856fa9886879
    supported_platforms:
      - architecture: arm_8
        operating_systems:
            - Linux
            - Darwin
        required_flags:
            - asimd
