name: Dilithium2
type: signature
claimed-nist-level: 2
length-public-key: 1312
length-secret-key: 2560
length-signature: 2420
nistkat-sha256: 3198fb788e0b18103add2e9ea5408cf6545a967f9bbed8be06a11915fcd87ad5
testvectors-sha256: 4ab35af63655a484b8409f7cd0722a41d351993027f0f3b5503d983b6ee8a655
principal-submitters:
  - Vadim Lyubashevsky
auxiliary-submitters:
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Peter Schwabe
  - Gregor Seiler
  - Damien Stehlé
implementations:
    - name: clean
      version: https://github.com/pq-crystals/dilithium/commit/918af1a6eaedcedf9fdd8aaaca6c1fccd5a7a51f via https://github.com/mkannwischer/package-pqclean/tree/0e93c0323cf84af6b437496ddae73a4cb79a6bcd/dilithium
    - name: avx2
      version: https://github.com/pq-crystals/dilithium/commit/918af1a6eaedcedf9fdd8aaaca6c1fccd5a7a51f via https://github.com/mkannwischer/package-pqclean/tree/0e93c0323cf84af6b437496ddae73a4cb79a6bcd/dilithium
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - aes
              - avx2
              - popcnt

    - name: aarch64
      version: https://github.com/neon-ntt/neon-ntt/tree/f88c7dd2bf03fb0dbdcccbf2fe437f7bb0a77441
      supported_platforms:
        - architecture: arm_8
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - asimd