name: LightSaber
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 672
length-ciphertext: 736
length-secret-key: 1568
length-shared-secret: 32
nistkat-sha256: dc2233ae221cfabbb1db5ab1a76c93967d37de9f87a8092561f95ab28eff6061
principal-submitters:
  - Jan-Pieter D'Anvers
  - Angshuman Karmakar
  - Sujoy Sinha Roy
  - Frederik Vercauteren
implementations:
    - name: clean
      version: https://github.com/KULeuven-COSIC/SABER/tree/509cc5ec3a7e12a751ccdd2ef5bd6e54e00bd350 via https://github.com/jschanck/package-pqclean/tree/1ae84c3c/saber
    - name: avx2
      version: https://github.com/KULeuven-COSIC/SABER/tree/509cc5ec3a7e12a751ccdd2ef5bd6e54e00bd350 via https://github.com/jschanck/package-pqclean/tree/1ae84c3c/saber
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
    - name: aarch64
      version: https://github.com/neon-ntt/neon-ntt/tree/b24c6d429124cd9f06e2cb1ee4e3f0e7cf4a511b
      supported_platforms:
          - architecture: arm_8
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - asimd
