name: Falcon-1024
type: signature
claimed-nist-level: 5
length-public-key: 1793
length-secret-key: 2305
length-signature: 1330
nistkat-sha256: ef2104e326221515621638ca03cd99802271bdd9907e2ae5fc7b8d19d696c584
testvectors-sha256: 14ee0e3f0ea4b9b25193a54eed9100b1bb1cf5dbc7813fd9dc9180c1ea1a1042
principal-submitters:
  - Thomas Prest
auxiliary-submitters:
  - Pierre-Alain Fouque
  - Jeffrey Hoffstein
  - Paul Kirchner
  - Vadim Lyubashevsky
  - Thomas Pornin
  - Thomas Ricosset
  - Gregor Seiler
  - William Whyte
  - Zhenfei Zhang
implementations:
    - name: clean
      version: 20190920
