name: HQC_192_2_CCA2
type: kem
claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 5884
length-ciphertext: 11749
length-secret-key: 5924
length-shared-secret: 64
nistkat-sha256: 838916e26585828d15cabb7a0a0b9dabb63986e432735b7f6cf2ee0e823bcca3
principal-submitters:
  - Carlos Aguilar Melchor
  - Nicolas Aragon
  - Slim Bettaieb
  - Loïc Bidoux
  - Olivier Blazy
  - Jean-Christophe Deneuville
  - Philippe Gaborit
  - Edoardo Persichetti
  - Gilles Zémor
auxiliary-submitters: []
implementations:
  - name: leaktime
    version: https://pqc-hqc.org/doc/hqc-reference-implementation_2019-08-24.zip
