name: ntruhps4096821
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 1230
length-secret-key: 1590
length-ciphertext: 1230
length-shared-secret: 32
nistkat-sha256: 0c5b6b159fab6eb677da469ec35aaa7e6b16162b315dcdb55a3b5da857e10519
principal-submitters:
  - John M. Schanck
auxiliary-submitters:
  - Cong Chen
  - Oussama Danba
  - Jeffrey Hoffstein
  - Andreas Hülsing
  - Joost Rijneveld
  - Tsunekazu Saito
  - Peter Schwabe
  - William Whyte
  - Keita Xagawa
  - Takashi Yamakawa
  - Zhenfei Zhang
implementations:
    - name: clean
      version: https://github.com/jschanck/ntru/tree/2d4df948 reference implementation
    - name: avx2
      version: https://github.com/jschanck/ntru/tree/2d4df948 avx2 implementation
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
                - bmi2
