name: gemss-red-256
type: signature
claimed-nist-level: 5
length-public-key: 3135591
length-secret-key: 32
length-signature: 75
nistkat-sha256: 624ec7629d3a835fc86a2f4cc1cb2386666b19c0f0c3df9b06f7006edb10726b
principal-submitters:
  - A. Casanova
  - J.-C. Faugere
  - G. Macario-Rat
  - J. Patarin
  - L. Perret
  - J. Ryckeghem
implementations:
    - name: clean
      version: GeMSS-Round2_V2.a
    - name: avx2
      version: GeMSS-Round2_V2.a
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
