name: Classic McEliece 348864
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 261120
length-secret-key: 6492
length-ciphertext: 96
length-shared-secret: 32
nistkat-sha256: 6f0f50626df15ce403c0c1d5f91648245282afebcac90e5db3595ce9b20b1817
principal-submitters:
  - Daniel J. Bernstein
  - Tung Chou
  - Tanja Lange
  - Ingo von Maurich
  - Rafael Misoczki
  - Ruben Niederhagen
  - Edoardo Persichetti
  - Christiane Peters
  - Peter Schwabe
  - Nicolas Sendrier
  - Jakub Szefer
  - Wen Wang
auxiliary-submitters: []
implementations:
    - name: clean
      version: SUPERCOP-20221025
    - name: avx2
      version: SUPERCOP-20221025
      supported_platforms:
        - architecture: x86_64
          operating_systems:
            - Linux
            - Darwin
          required_flags:
            - avx2
            - popcnt