name: Classic McEliece 348864
type: kem
claimed-nist-level: 1
claimed-security: IND-CCA2
length-public-key: 261120
length-secret-key: 6452
length-ciphertext: 128
length-shared-secret: 32
nistkat-sha256: f0a166a9115a0c8481c85aee3fe901729a21a8a84a5d2b871fb99fc50223046b
principal-submitters:
  - Daniel J. Bernstein
  - Tung Chou
  - Tanja Lange
  - Ingo von Maurich
  - Rafael Misoczki
  - Ruben Niederhagen
  - Edoardo Persichetti
  - Christiane Peters
  - Peter Schwabe
  - Nicolas Sendrier
  - Jakub Szefer
  - Wen Wang
auxiliary-submitters: []
implementations:
    - name: clean
      version: SUPERCOP-20191221
    - name: vec
      version: SUPERCOP-20191221
    - name: sse
      version: SUPERCOP-20191221
      supported_platforms:
        - architecture: x86_64
          operating_systems:
            - Linux
            - Darwin
          required_flags:
            - sse4_1
            - popcnt
    - name: avx
      version: SUPERCOP-20191221
      supported_platforms:
        - architecture: x86_64
          operating_systems:
            - Linux
            - Darwin
          required_flags:
            - avx2
            - popcnt
