name: ML-KEM-1024
type: kem
claimed-nist-level: 5
claimed-security: IND-CCA2
length-public-key: 1568
length-ciphertext: 1568
length-secret-key: 3168
length-shared-secret: 32
nistkat-sha256: f580d851e5fb27e6876e5e203fa18be4cdbfd49e05d48fec3d3992c8f43a13e6
principal-submitters:
  - Peter Schwabe
auxiliary-submitters:
  - Roberto Avanzi
  - Joppe Bos
  - Léo Ducas
  - Eike Kiltz
  - Tancrède Lepoint
  - Vadim Lyubashevsky
  - John M. Schanck
  - Gregor Seiler
  - Damien Stehlé
  - Jintai Ding
implementations:
    - name: clean
      version: https://github.com/pq-crystals/kyber/commit/3c874cddd5fdaf4a7bd13f7e2e4d98a2a1eb8dc4 via https://github.com/mkannwischer/package-pqclean/tree/5c4c882/kyber
    - name: avx2
      version: https://github.com/pq-crystals/kyber/commit/3c874cddd5fdaf4a7bd13f7e2e4d98a2a1eb8dc4 via https://github.com/mkannwischer/package-pqclean/tree/5c4c882/kyber
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - aes
              - avx2
              - bmi2
              - popcnt
    - name: aarch64
      version: https://github.com/neon-ntt/neon-ntt/tree/70cdc9601b8fce9b6c0cef4faf168b6c4c4ddc4c
      supported_platforms:
        - architecture: arm_8
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - asimd
